CppCMS: booster::locale::period Namespace Reference
booster::locale::period Namespace Reference
Date, Time, Timezone and Calendar manipulations
Namespace that contains various types for manipulation with dates.
Namespaces
marks
This namespace holds a enum of various period types like era, year, month, etc..
Classes
class period_type
This class holds a type that represents certain period of time like year, hour, second and so on.
Functions
period_type invalid ()
period_type era ()
period_type year ()
period_type extended_year ()
period_type month ()
period_type day ()
period_type day_of_year ()
period_type day_of_week ()
period_type day_of_week_in_month ()
period_type day_of_week_local ()
period_type hour ()
period_type hour_12 ()
period_type am_pm ()
period_type minute ()
period_type second ()
period_type week_of_year ()
period_type week_of_month ()
period_type first_day_of_week ()
date_time_period era (int v)
date_time_period year (int v)
date_time_period extended_year (int v)
date_time_period month (int v)
date_time_period day (int v)
date_time_period day_of_year (int v)
date_time_period day_of_week (int v)
date_time_period day_of_week_in_month (int v)
date_time_period day_of_week_local (int v)
date_time_period hour (int v)
date_time_period hour_12 (int v)
date_time_period am_pm (int v)
date_time_period minute (int v)
date_time_period second (int v)
date_time_period week_of_year (int v)
date_time_period week_of_month (int v)
date_time_period first_day_of_week (int v)
date_time_period january ()
date_time_period february ()
date_time_period march ()
date_time_period april ()
date_time_period may ()
date_time_period june ()
date_time_period july ()
date_time_period august ()
date_time_period september ()
date_time_period october ()
date_time_period november ()
date_time_period december ()
date_time_period sunday ()
date_time_period monday ()
date_time_period tuesday ()
date_time_period wednesday ()
date_time_period thursday ()
date_time_period friday ()
date_time_period saturday ()
date_time_period am ()
date_time_period pm ()
date_time_period operator+ (period::period_type f)
date_time_period operator- (period::period_type f)
template<typename T >
date_time_period operator* (period::period_type f, T v)
template<typename T >
date_time_period operator* (T v, period::period_type f)
template<typename T >
date_time_period operator* (T v, date_time_period f)
template<typename T >
date_time_period operator* (date_time_period f, T v)
int era (date_time const &dt)
int year (date_time const &dt)
int extended_year (date_time const &dt)
int month (date_time const &dt)
int day (date_time const &dt)
int day_of_year (date_time const &dt)
int day_of_week (date_time const &dt)
int day_of_week_in_month (date_time const &dt)
int day_of_week_local (date_time const &dt)
int hour (date_time const &dt)
int hour_12 (date_time const &dt)
int am_pm (date_time const &dt)
int minute (date_time const &dt)
int second (date_time const &dt)
int week_of_year (date_time const &dt)
int week_of_month (date_time const &dt)
int first_day_of_week (date_time const &dt)
int era (date_time_duration const &dt)
int year (date_time_duration const &dt)
int extended_year (date_time_duration const &dt)
int month (date_time_duration const &dt)
int day (date_time_duration const &dt)
int day_of_year (date_time_duration const &dt)
int day_of_week (date_time_duration const &dt)
int day_of_week_in_month (date_time_duration const &dt)
int day_of_week_local (date_time_duration const &dt)
int hour (date_time_duration const &dt)
int hour_12 (date_time_duration const &dt)
int am_pm (date_time_duration const &dt)
int minute (date_time_duration const &dt)
int second (date_time_duration const &dt)
int week_of_year (date_time_duration const &dt)
int week_of_month (date_time_duration const &dt)
int first_day_of_week (date_time_duration const &dt)
Detailed Description
Namespace that contains various types for manipulation with dates.
Function Documentation
date_time_period booster::locale::period::am () inline
Get predefined constant for AM (Ante Meridiem)
References am_pm().
period_type booster::locale::period::am_pm () inline
Get period_type for: am or pm marker [0..1]
References booster::locale::period::marks::am_pm.
Referenced by am(), am_pm(), and pm().
date_time_period booster::locale::period::am_pm (int v) inline
Get date_time_period for: am or pm marker [0..1]
References am_pm().
int booster::locale::period::am_pm (date_time const & dt) inline
Extract from date_time numerical value of am or pm marker [0..1]
References am_pm(), and booster::locale::date_time::get().
int booster::locale::period::am_pm (date_time_duration const & dt) inline
Extract from date_time_duration numerical value of duration in am or pm markers
References am_pm(), and booster::locale::date_time_duration::get().
date_time_period booster::locale::period::april () inline
Get predefined constant for April
References month().
date_time_period booster::locale::period::august () inline
Get predefined constant for August
References month().
period_type booster::locale::period::day () inline
Get period_type for: The day of month, calendar specific, in Gregorian [1..31]
References booster::locale::period::marks::day.
Referenced by day().
date_time_period booster::locale::period::day (int v) inline
Get date_time_period for: The day of month, calendar specific, in Gregorian [1..31]
References day().
int booster::locale::period::day (date_time const & dt) inline
Extract from date_time numerical value of The day of month, calendar specific, in Gregorian [1..31]
References day(), and booster::locale::date_time::get().
int booster::locale::period::day (date_time_duration const & dt) inline
Extract from date_time_duration numerical value of duration in days of month
References day(), and booster::locale::date_time_duration::get().
period_type booster::locale::period::day_of_week () inline
Get period_type for: Day of week, Sunday=1, Monday=2,..., Saturday=7.
Note that that updating this value respects local day of week, so for example, If first day of week is Monday and the current day is Tuesday then setting the value to Sunday (1) would forward the date by 5 days forward and not backward by two days as it could be expected if the numbers were taken as is.
References booster::locale::period::marks::day_of_week.
Referenced by day_of_week(), friday(), monday(), saturday(), sunday(), thursday(), tuesday(), and wednesday().
date_time_period booster::locale::period::day_of_week (int v) inline
Get date_time_period for: Day of week, Sunday=1, Monday=2,..., Saturday=7.
Note that that updating this value respects local day of week, so for example, If first day of week is Monday and the current day is Tuesday then setting the value to Sunday (1) would forward the date by 5 days forward and not backward by two days as it could be expected if the numbers were taken as is.
References day_of_week().
int booster::locale::period::day_of_week (date_time const & dt) inline
Extract from date_time numerical value of Day of week, Sunday=1, Monday=2,..., Saturday=7.
Note that that updating this value respects local day of week, so for example, If first day of week is Monday and the current day is Tuesday then setting the value to Sunday (1) would forward the date by 5 days forward and not backward by two days as it could be expected if the numbers were taken as is.
References day_of_week(), and booster::locale::date_time::get().
int booster::locale::period::day_of_week (date_time_duration const & dt) inline
Extract from date_time_duration numerical value of duration in days of week
References day_of_week(), and booster::locale::date_time_duration::get().
period_type booster::locale::period::day_of_week_in_month () inline
Get period_type for: Original number of the day of the week in month. For example 1st Sunday, 2nd Sunday, etc. in Gregorian [1..5]
References booster::locale::period::marks::day_of_week_in_month.
Referenced by day_of_week_in_month().
date_time_period booster::locale::period::day_of_week_in_month (int v) inline
Get date_time_period for: Original number of the day of the week in month. For example 1st Sunday, 2nd Sunday, etc. in Gregorian [1..5]
References day_of_week_in_month().
int booster::locale::period::day_of_week_in_month (date_time const & dt) inline
Extract from date_time numerical value of Original number of the day of the week in month. For example 1st Sunday, 2nd Sunday, etc. in Gregorian [1..5]
References day_of_week_in_month(), and booster::locale::date_time::get().
int booster::locale::period::day_of_week_in_month (date_time_duration const & dt) inline
Extract from date_time_duration numerical value of duration in original number of the day of the week in month
References day_of_week_in_month(), and booster::locale::date_time_duration::get().
period_type booster::locale::period::day_of_week_local () inline
Get period_type for: Local day of week, for example in France Monday is 1, in US Sunday is 1, [1..7]
References booster::locale::period::marks::day_of_week_local.
Referenced by day_of_week_local().
date_time_period booster::locale::period::day_of_week_local (int v) inline
Get date_time_period for: Local day of week, for example in France Monday is 1, in US Sunday is 1, [1..7]
References day_of_week_local().
int booster::locale::period::day_of_week_local (date_time const & dt) inline
Extract from date_time numerical value of Local day of week, for example in France Monday is 1, in US Sunday is 1, [1..7]
References day_of_week_local(), and booster::locale::date_time::get().
int booster::locale::period::day_of_week_local (date_time_duration const & dt) inline
Extract from date_time_duration numerical value of duration in local day of week
References day_of_week_local(), and booster::locale::date_time_duration::get().
period_type booster::locale::period::day_of_year () inline
Get period_type for: The number of day in year, starting from 1, in Gregorian [1..366]
References booster::locale::period::marks::day_of_year.
Referenced by day_of_year().
date_time_period booster::locale::period::day_of_year (int v) inline
Get date_time_period for: The number of day in year, starting from 1, in Gregorian [1..366]
References day_of_year().
int booster::locale::period::day_of_year (date_time const & dt) inline
Extract from date_time numerical value of The number of day in year, starting from 1, in Gregorian [1..366]
References day_of_year(), and booster::locale::date_time::get().
int booster::locale::period::day_of_year (date_time_duration const & dt) inline
Extract from date_time_duration numerical value of duration in days of year
References day_of_year(), and booster::locale::date_time_duration::get().
date_time_period booster::locale::period::december () inline
Get predefined constant for December
References month().
period_type booster::locale::period::era () inline
Get period_type for: Era i.e. AC, BC in Gregorian and Julian calendar, range [0,1]
References booster::locale::period::marks::era.
Referenced by era().
date_time_period booster::locale::period::era (int v) inline
Get date_time_period for: Era i.e. AC, BC in Gregorian and Julian calendar, range [0,1]
References era().
int booster::locale::period::era (date_time const & dt) inline
Extract from date_time numerical value of Era i.e. AC, BC in Gregorian and Julian calendar, range [0,1]
References era(), and booster::locale::date_time::get().
int booster::locale::period::era (date_time_duration const & dt) inline
Extract from date_time_duration numerical value of duration in Era i.e. AC, BC in Gregorian and Julian calendar, range [0,1]
References era(), and booster::locale::date_time_duration::get().
period_type booster::locale::period::extended_year () inline
Get period_type for: Extended year for Gregorian/Julian calendars, where 1 BC == 0, 2 BC == -1.
References booster::locale::period::marks::extended_year.
Referenced by extended_year().
date_time_period booster::locale::period::extended_year (int v) inline
Get date_time_period for: Extended year for Gregorian/Julian calendars, where 1 BC == 0, 2 BC == -1.
References extended_year().
int booster::locale::period::extended_year (date_time const & dt) inline
Extract from date_time numerical value of Extended year for Gregorian/Julian calendars, where 1 BC == 0, 2 BC == -1.
References extended_year(), and booster::locale::date_time::get().
int booster::locale::period::extended_year (date_time_duration const & dt) inline
Extract from date_time_duration numerical value of duration in extended years (for Gregorian/Julian calendars, where 1 BC == 0, 2 BC == -1).
References extended_year(), and booster::locale::date_time_duration::get().
date_time_period booster::locale::period::february () inline
Get predefined constant for February
References month().
period_type booster::locale::period::first_day_of_week () inline
Get period_type for: First day of week, constant, for example Sunday in US = 1, Monday in France = 2
References booster::locale::period::marks::first_day_of_week.
Referenced by first_day_of_week().
date_time_period booster::locale::period::first_day_of_week (int v) inline
Get date_time_period for: First day of week, constant, for example Sunday in US = 1, Monday in France = 2
References first_day_of_week().
int booster::locale::period::first_day_of_week (date_time const & dt) inline
Extract from date_time numerical value of First day of week, constant, for example Sunday in US = 1, Monday in France = 2
References first_day_of_week(), and booster::locale::date_time::get().
int booster::locale::period::first_day_of_week (date_time_duration const & dt) inline
Extract from date_time_duration numerical value of duration in the first day of week
References first_day_of_week(), and booster::locale::date_time_duration::get().
date_time_period booster::locale::period::friday () inline
Get predefined constant for Friday
References day_of_week().
period_type booster::locale::period::hour () inline
Get period_type for: 24 clock hour [0..23]
References booster::locale::period::marks::hour.
Referenced by hour().
date_time_period booster::locale::period::hour (int v) inline
Get date_time_period for: 24 clock hour [0..23]
References hour().
int booster::locale::period::hour (date_time const & dt) inline
Extract from date_time numerical value of 24 clock hour [0..23]
References booster::locale::date_time::get(), and hour().
int booster::locale::period::hour (date_time_duration const & dt) inline
Extract from date_time_duration numerical value of duration in hours
References booster::locale::date_time_duration::get(), and hour().
period_type booster::locale::period::hour_12 () inline
Get period_type for: 12 clock hour [0..11]
References booster::locale::period::marks::hour_12.
Referenced by hour_12().
date_time_period booster::locale::period::hour_12 (int v) inline
Get date_time_period for: 12 clock hour [0..11]
References hour_12().
int booster::locale::period::hour_12 (date_time const & dt) inline
Extract from date_time numerical value of 12 clock hour [0..11]
References booster::locale::date_time::get(), and hour_12().
int booster::locale::period::hour_12 (date_time_duration const & dt) inline
Extract from date_time_duration numerical value of duration in 12 clock hours
References booster::locale::date_time_duration::get(), and hour_12().
period_type booster::locale::period::invalid () inline
Get period_type for: special invalid value, should not be used directly
References booster::locale::period::marks::invalid.
date_time_period booster::locale::period::january () inline
Get predefined constant for January
References month().
date_time_period booster::locale::period::july () inline
Get predefined constant for July
References month().
date_time_period booster::locale::period::june () inline
Get predefined constant for June
References month().
date_time_period booster::locale::period::march () inline
Get predefined constant for March
References month().
date_time_period booster::locale::period::may () inline
Get predefined constant for May
References month().
period_type booster::locale::period::minute () inline
Get period_type for: minute [0..59]
References booster::locale::period::marks::minute.
Referenced by minute().
date_time_period booster::locale::period::minute (int v) inline
Get date_time_period for: minute [0..59]
References minute().
int booster::locale::period::minute (date_time const & dt) inline
Extract from date_time numerical value of minute [0..59]
References booster::locale::date_time::get(), and minute().
int booster::locale::period::minute (date_time_duration const & dt) inline
Extract from date_time_duration numerical value of duration in minutes
References booster::locale::date_time_duration::get(), and minute().
date_time_period booster::locale::period::monday () inline
Get predefined constant for Monday
References day_of_week().
period_type booster::locale::period::month () inline
Get period_type for: The month of year, calendar specific, in Gregorian [0..11]
References booster::locale::period::marks::month.
Referenced by april(), august(), december(), february(), january(), july(), june(), march(), may(), month(), november(), october(), and september().
date_time_period booster::locale::period::month (int v) inline
Get date_time_period for: The month of year, calendar specific, in Gregorian [0..11]
References month().
int booster::locale::period::month (date_time const & dt) inline
Extract from date_time numerical value of The month of year, calendar specific, in Gregorian [0..11]
References booster::locale::date_time::get(), and month().
int booster::locale::period::month (date_time_duration const & dt) inline
Extract from date_time_duration numerical value of duration in months
References booster::locale::date_time_duration::get(), and month().
date_time_period booster::locale::period::november () inline
Get predefined constant for November
References month().
date_time_period booster::locale::period::october () inline
Get predefined constant for October
References month().
template<typename T > date_time_period booster::locale::period::operator* (period::period_type f, T v)
Create date_time_period of type f with value v.
template<typename T > date_time_period booster::locale::period::operator* (T v, period::period_type f)
Create date_time_period of type f with value v.
template<typename T > date_time_period booster::locale::period::operator* (T v, date_time_period f)
Create date_time_period of type f with value v.
References booster::locale::date_time_period::type, and booster::locale::date_time_period::value.
template<typename T > date_time_period booster::locale::period::operator* (date_time_period f, T v)
Create date_time_period of type f with value v.
References booster::locale::date_time_period::type, and booster::locale::date_time_period::value.
date_time_period booster::locale::period::operator+ (period::period_type f) inline
convert period_type to date_time_period(f,1)
date_time_period booster::locale::period::operator- (period::period_type f) inline
convert period_type to date_time_period(f,-1)
date_time_period booster::locale::period::pm () inline
Get predefined constant for PM (Post Meridiem)
References am_pm().
date_time_period booster::locale::period::saturday () inline
Get predefined constant for Saturday
References day_of_week().
period_type booster::locale::period::second () inline
Get period_type for: second [0..59]
References booster::locale::period::marks::second.
Referenced by second().
date_time_period booster::locale::period::second (int v) inline
Get date_time_period for: second [0..59]
References second().
int booster::locale::period::second (date_time const & dt) inline
Extract from date_time numerical value of second [0..59]
References booster::locale::date_time::get(), and second().
int booster::locale::period::second (date_time_duration const & dt) inline
Extract from date_time_duration numerical value of duration in seconds
References booster::locale::date_time_duration::get(), and second().
date_time_period booster::locale::period::september () inline
Get predefined constant for September
References month().
date_time_period booster::locale::period::sunday () inline
Get predefined constant for Sunday
References day_of_week().
date_time_period booster::locale::period::thursday () inline
Get predefined constant for Thursday
References day_of_week().
date_time_period booster::locale::period::tuesday () inline
Get predefined constant for Tuesday
References day_of_week().
date_time_period booster::locale::period::wednesday () inline
Get predefined constant for Wednesday
References day_of_week().
period_type booster::locale::period::week_of_month () inline
Get period_type for: The week number within current month
References booster::locale::period::marks::week_of_month.
Referenced by week_of_month().
date_time_period booster::locale::period::week_of_month (int v) inline
Get date_time_period for: The week number within current month
References week_of_month().
int booster::locale::period::week_of_month (date_time const & dt) inline
Extract from date_time numerical value of The week number within current month
References booster::locale::date_time::get(), and week_of_month().
int booster::locale::period::week_of_month (date_time_duration const & dt) inline
Extract from date_time_duration numerical value of duration in The week number within current month
References booster::locale::date_time_duration::get(), and week_of_month().
period_type booster::locale::period::week_of_year () inline
Get period_type for: The week number in the year
References booster::locale::period::marks::week_of_year.
Referenced by week_of_year().
date_time_period booster::locale::period::week_of_year (int v) inline
Get date_time_period for: The week number in the year
References week_of_year().
int booster::locale::period::week_of_year (date_time const & dt) inline
Extract from date_time numerical value of The week number in the year
References booster::locale::date_time::get(), and week_of_year().
int booster::locale::period::week_of_year (date_time_duration const & dt) inline
Extract from date_time_duration numerical value of duration in the week number in the year
References booster::locale::date_time_duration::get(), and week_of_year().
period_type booster::locale::period::year () inline
Get period_type for: Year, it is calendar specific, for example 2011 in Gregorian calendar.
References booster::locale::period::marks::year.
Referenced by year().
date_time_period booster::locale::period::year (int v) inline
Get date_time_period for: Year, it is calendar specific, for example 2011 in Gregorian calendar.
References year().
int booster::locale::period::year (date_time const & dt) inline
Extract from date_time numerical value of Year, it is calendar specific, for example 2011 in Gregorian calendar.
References booster::locale::date_time::get(), and year().
int booster::locale::period::year (date_time_duration const & dt) inline
Extract from date_time_duration numerical value of duration in years
References booster::locale::date_time_duration::get(), and year().